### ISSUE TITLE
Doesn't build with haskell-src-exts-1.18

### ISSUE THREAD

**Issue by RyanGlScott** [23Skidoo/pointful#10]
```
Building pointful-1.0.8...
Preprocessing library pointful-1.0.8...
[1 of 2] Compiling Lambdabot.Parser ( Lambdabot/Parser.hs, dist/build/Lambdabot/Parser.o )
[2 of 2] Compiling Lambdabot.Pointful ( Lambdabot/Pointful.hs, dist/build/Lambdabot/Pointful.o )

Lambdabot/Pointful.hs:27:39: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the first argument of ‘S.Set’, namely ‘Name’
      In the type signature:
        varsBoundHere :: Data d => d -> S.Set Name

Lambdabot/Pointful.hs:38:40: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the type signature:
        foldFreeVars :: forall a d.
                        Data d => (Name -> S.Set Name -> a) -> ([a] -> a) -> d -> a

Lambdabot/Pointful.hs:38:54: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the first argument of ‘S.Set’, namely ‘Name’
      In the type signature:
        foldFreeVars :: forall a d.
                        Data d => (Name -> S.Set Name -> a) -> ([a] -> a) -> d -> a

Lambdabot/Pointful.hs:62:34: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the first argument of ‘S.Set’, namely ‘Name’
      In the type signature:
        freeVars :: Data d => d -> S.Set Name

Lambdabot/Pointful.hs:66:23: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the type signature:
        countOcc :: Data d => Name -> d -> Int

Lambdabot/Pointful.hs:72:34: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the first argument of ‘M.Map’, namely ‘Name’
      In the type signature:
        substAvoiding :: Data d => M.Map Name Exp -> S.Set Name -> d -> d

Lambdabot/Pointful.hs:72:39: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the second argument of ‘M.Map’, namely ‘Exp’
      In the type signature:
        substAvoiding :: Data d => M.Map Name Exp -> S.Set Name -> d -> d

Lambdabot/Pointful.hs:72:52: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the first argument of ‘S.Set’, namely ‘Name’
      In the type signature:
        substAvoiding :: Data d => M.Map Name Exp -> S.Set Name -> d -> d

Lambdabot/Pointful.hs:103:32: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the first argument of ‘M.Map’, namely ‘Name’
      In the type signature:
        renameBinds :: Data d =>
                       M.Map Name Exp
                       -> S.Set Name -> d -> (M.Map Name Exp, S.Set Name, d)

Lambdabot/Pointful.hs:103:37: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the second argument of ‘M.Map’, namely ‘Exp’
      In the type signature:
        renameBinds :: Data d =>
                       M.Map Name Exp
                       -> S.Set Name -> d -> (M.Map Name Exp, S.Set Name, d)

Lambdabot/Pointful.hs:103:50: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the first argument of ‘S.Set’, namely ‘Name’
      In the type signature:
        renameBinds :: Data d =>
                       M.Map Name Exp
                       -> S.Set Name -> d -> (M.Map Name Exp, S.Set Name, d)

Lambdabot/Pointful.hs:103:70: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the first argument of ‘M.Map’, namely ‘Name’
      In the type signature:
        renameBinds :: Data d =>
                       M.Map Name Exp
                       -> S.Set Name -> d -> (M.Map Name Exp, S.Set Name, d)

Lambdabot/Pointful.hs:103:75: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the second argument of ‘M.Map’, namely ‘Exp’
      In the type signature:
        renameBinds :: Data d =>
                       M.Map Name Exp
                       -> S.Set Name -> d -> (M.Map Name Exp, S.Set Name, d)

Lambdabot/Pointful.hs:103:86: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the first argument of ‘S.Set’, namely ‘Name’
      In the type signature:
        renameBinds :: Data d =>
                       M.Map Name Exp
                       -> S.Set Name -> d -> (M.Map Name Exp, S.Set Name, d)

Lambdabot/Pointful.hs:141:22: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the type signature:
        freshNameAvoiding :: Name -> S.Set Name -> Name

Lambdabot/Pointful.hs:141:36: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the first argument of ‘S.Set’, namely ‘Name’
      In the type signature:
        freshNameAvoiding :: Name -> S.Set Name -> Name

Lambdabot/Pointful.hs:141:44: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the type signature:
        freshNameAvoiding :: Name -> S.Set Name -> Name

Lambdabot/Pointful.hs:153:14: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        optimizeD :: Decl -> Decl

Lambdabot/Pointful.hs:153:22: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        optimizeD :: Decl -> Decl

Lambdabot/Pointful.hs:166:16: error:
    • Expecting one more argument to ‘Rhs’
      Expected a type, but ‘Rhs’ has kind ‘* -> *’
    • In the type signature:
        optimizeRhs :: Rhs -> Rhs

Lambdabot/Pointful.hs:166:23: error:
    • Expecting one more argument to ‘Rhs’
      Expected a type, but ‘Rhs’ has kind ‘* -> *’
    • In the type signature:
        optimizeRhs :: Rhs -> Rhs

Lambdabot/Pointful.hs:170:14: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        optimizeE :: Exp -> Exp

Lambdabot/Pointful.hs:170:21: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        optimizeE :: Exp -> Exp

Lambdabot/Pointful.hs:226:12: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        uncomb' :: Exp -> Exp

Lambdabot/Pointful.hs:226:19: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        uncomb' :: Exp -> Exp

Lambdabot/Pointful.hs:261:22: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the first argument of ‘M.Map’, namely ‘Name’
      In the type signature:
        combinators :: M.Map Name Exp

Lambdabot/Pointful.hs:261:27: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the second argument of ‘M.Map’, namely ‘Exp’
      In the type signature:
        combinators :: M.Map Name Exp
```

**Comment by 23Skidoo** [comment]
GHC version?

**Comment by 23Skidoo** [comment]
Ah ok, I see that the problem is `haskell-src-exts`.

**Comment by RyanGlScott** [comment]
```
$ cabal configure -v2
/opt/ghc/7.10.3/bin/ghc --numeric-version
looking for tool ghc-pkg near compiler in /opt/ghc/7.10.3/bin
found ghc-pkg in /opt/ghc/7.10.3/bin/ghc-pkg
/opt/ghc/7.10.3/bin/ghc-pkg --version
/opt/ghc/7.10.3/bin/ghc --supported-languages
/opt/ghc/7.10.3/bin/ghc --info
Reading available packages...
Choosing modular solver.
Resolving dependencies...
Configuring pointful-1.0.8...
Dependency base ==4.8.2.0: using base-4.8.2.0
Dependency containers ==0.5.6.2: using containers-0.5.6.2
Dependency haskell-src-exts ==1.18.2: using haskell-src-exts-1.18.2
Dependency mtl ==2.2.1: using mtl-2.2.1
Dependency syb ==0.6: using syb-0.6
Dependency transformers ==0.4.2.0: using transformers-0.4.2.0
```

**Comment by 23Skidoo** [comment]
Updated version bounds for the released versions on Hackage.

**Comment by 23Skidoo** [comment]
Looks like this was caused by https://github.com/haskell-suite/haskell-src-exts/commit/38c2befdd07e20a268f8d6c685cca90a2992ed67, which made annotated AST the default.

**Comment by 23Skidoo** [comment]
Tried adapting the code myself, but it's a bit too involved; will wait until upstream fixes it.

Upstream ticket: https://github.com/lambdabot/lambdabot/issues/146.

**Comment by 23Skidoo** [comment]
Fixed, new version released.
